package com.r1.launcher.hermes

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import java.util.Base64

/**
 * Pairing payload encoded in a Hermes setup QR. Generated by
 * `scripts/hermes-setup.sh`; the key is optional so LAN deploys without auth
 * (no `API_SERVER_KEY`) still pair cleanly.
 */
data class HermesSetupCode(val url: String, val key: String?)

private const val PAIR_URI_PREFIX = "r1-hermes://v1/"

private val json = Json { ignoreUnknownKeys = true }

/**
 * Decode the QR-encoded pairing payload into [HermesSetupCode], or null if the
 * input is unrecognised. Accepted forms:
 *
 *  - `r1-hermes://v1/<url-safe-base64-of-json>` (what the setup script emits)
 *  - raw URL-safe base64 of `{"url":"…","key":"…"}`
 *  - raw JSON `{"url":"…","key":"…"}` (for hand-rolled QR generators)
 *
 * The `url` field is required and non-blank. Unknown fields (`v`, etc.) are
 * tolerated.
 */
fun decodeHermesSetupCode(raw: String): HermesSetupCode? {
    val trimmed = raw.trim().removePrefix(PAIR_URI_PREFIX)
    if (trimmed.isEmpty()) return null

    parseJson(trimmed)?.let { return it }

    val padded = trimmed
        .replace('-', '+')
        .replace('_', '/')
        .let { s ->
            val rem = s.length % 4
            if (rem == 0) s else s + "=".repeat(4 - rem)
        }
    return try {
        val decoded = String(Base64.getDecoder().decode(padded), Charsets.UTF_8)
        parseJson(decoded)
    } catch (_: Throwable) {
        null
    }
}

private fun parseJson(text: String): HermesSetupCode? = try {
    val obj = json.parseToJsonElement(text) as? JsonObject ?: return null
    val url = obj["url"]?.jsonPrimitive?.contentOrNull?.trim()?.takeIf { it.isNotEmpty() } ?: return null
    val key = obj["key"]?.jsonPrimitive?.contentOrNull?.trim()?.takeIf { it.isNotEmpty() }
    HermesSetupCode(url = url, key = key)
} catch (_: Throwable) {
    null
}
